<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width,initial-scale=1"/>
	<title>System Information</title>
	<link rel="stylesheet" type="text/css" href="assets/css/style.css">
</head>
<body>
	<div class="container">
		<div class="col">
			<table>
				<tr>
					<th>Architecture:</th>
					<td>x86_64</td>
				</tr>
				<tr>
					<th>CPUop-mode(s):</th>
					<td>32-bit,64-bit</td>
				</tr>
				<tr>
					<th>ByteOrder:</th>
					<td>LittleEndian</td>
				</tr>
				<tr>
					<th>Addresssizes:</th>
					<td>48bitsphysical,48bitsvirtual</td>
				</tr>
				<tr>
					<th>CPU(s):</th>
					<td>2</td>
				</tr>
				<tr>
					<th>On-lineCPU(s)list:</th>
					<td>0,1</td>
				</tr>
				<tr>
					<th>Thread(s)percore:</th>
					<td>2</td>
				</tr>
				<tr>
					<th>Core(s)persocket:</th>
					<td>1</td>
				</tr>
				<tr>
					<th>Socket(s):</th>
					<td>1</td>
				</tr>
				<tr>
					<th>NUMAnode(s):</th>
					<td>1</td>
				</tr>
				<tr>
					<th>VendorID:</th>
					<td>AuthenticAMD</td>
				</tr>
				<tr>
					<th>CPUfamily:</th>
					<td>21</td>
				</tr>
				<tr>
					<th>Model:</th>
					<td>16</td>
				</tr>
				<tr>
					<th>Modelname:</th>
					<td>AMDA4-4300MAPUwithRadeon(tm)HDGraphics</td>
				</tr>
				<tr>
					<th>Stepping:</th>
					<td>1</td>
				</tr>
				<tr>
					<th>Frequencyboost:</th>
					<td>enabled</td>
				</tr>
				<tr>
					<th>CPUMHz:</th>
					<td>1400.000</td>
				</tr>
				<tr>
					<th>CPUmaxMHz:</th>
					<td>2500.0000</td>
				</tr>
				<tr>
					<th>CPUminMHz:</th>
					<td>1400.0000</td>
				</tr>
				<tr>
					<th>BogoMIPS:</th>
					<td>4990.15</td>
				</tr>
				<tr>
					<th>Virtualization:</th>
					<td>AMD-V</td>
				</tr>
				<tr>
					<th>L1dcache:</th>
					<td>16KiB</td>
				</tr>
				<tr>
					<th>L1icache:</th>
					<td>64KiB</td>
				</tr>
				<tr>
					<th>L2cache:</th>
					<td>1MiB</td>
				</tr>
				<tr>
					<th>NUMAnode0CPU(s):</th>
					<td>0,1</td>
				</tr>
				<tr>
					<th>VulnerabilityItlbmultihit:</th>
					<td>Notaffected</td>
				</tr>
				<tr>
					<th>VulnerabilityL1tf:</th>
					<td>Notaffected</td>
				</tr>
				<tr>
					<th>VulnerabilityMds:</th>
					<td>Notaffected</td>
				</tr>
				<tr>
					<th>VulnerabilityMeltdown:</th>
					<td>Notaffected</td>
				</tr>
				<tr>
					<th>VulnerabilityMmiostaledata:</th>
					<td>Notaffected</td>
				</tr>
				<tr>
					<th>VulnerabilityRetbleed:</th>
					<td>Mitigation;untrainedreturnthunk;SMTvulnerable</td>
				</tr>
				<tr>
					<th>VulnerabilitySpecstorebypass:</th>
					<td>Mitigation;SpeculativeStoreBypassdisabledviaprctlandseccomp</td>
				</tr>
				<tr>
					<th>VulnerabilitySpectrev1:</th>
					<td>Mitigation;usercopy/swapgsbarriersand__userpointersanitization</td>
				</tr>
				<tr>
					<th>VulnerabilitySpectrev2:</th>
					<td>Mitigation;Retpolines,IBPBconditional,STIBPdisabled,RSBfilling,PBRSB-eIBRSNotaffected</td>
				</tr>
				<tr>
					<th>VulnerabilitySrbds:</th>
					<td>Notaffected</td>
				</tr>
				<tr>
					<th>VulnerabilityTsxasyncabort:</th>
					<td>Notaffected</td>
				</tr>
				<tr>
					<th>Flags:</th>
					<td>fpuvmedepsetscmsrpaemcecx8apicsepmtrrpgemcacmovpatpse36clflushmmxfxsrssesse2htsyscallnxmmxextfxsr_optpdpe1gbrdtscplmconstant_tscrep_goodnoplnonstop_tsccpuidextd_apicidaperfmperfpnipclmulqdqmonitorssse3fmacx16sse4_1sse4_2popcntaesxsaveavxf16clahf_lmcmp_legacysvmextapiccr8_legacyabmsse4amisalignsse3dnowprefetchosvwibsxopskinitwdtlwpfma4tcenodeid_msrtbmtopoextperfctr_coreperfctr_nbcpbhw_pstatessbdibpbvmmcallbmi1aratnptlbrvsvm_locknrip_savetsc_scalevmcb_cleanflushbyasiddecodeassistspausefilterpfthreshold</td>
				</tr>
			</table>
		</div>
	</div>
</body>
</html>